SELECT YEAR(O.SALES_DATE) AS YEAR,
MONTH(O.SALES_DATE) AS MONTH,
GENDER,
COUNT(distinct(O.USER_ID)) AS USERS
FROM USER_INFO AS U
JOIN ONLINE_SALE AS O
ON O.USER_ID = U.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER
;